import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/globals.css";
import Provider from "./provider";
import { Toaster } from "@repo/ui/components/toaster";
import { Navbar } from "@repo/ui/components/navbar";
import { headers } from "next/headers";
import Loading from "./loading";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const url = headers().get('x-pathname') || "";
 
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <Toaster />
          {url == "/user/create"?"":<Navbar></Navbar>}
          {children}
        </Provider>
      </body>
    </html>
  );
}
